meta:
  run-mode: debug
  log-path: ./logs/
  log-name: console

bot:
  token: xxx
  poller-timeout: 3600 # second

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_scut_notifier
  user: root
  password: 123
  max-idle: 10
  max-active: 100
  max-lifetime: 3600 # second

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 5000 # microsecond
  read-timeout: 5000 # microsecond
  write-timeout: 5000 # microsecond
  max-idle: 10
  max-active: 100
  max-lifetime: 3600 # second
  idle-timeout: 300 # second

send:
  range: 30 # day
  max-count: 10 # wechat

task:
  cron: 0 0/1 * * * *
