meta:
  run-mode: debug
  log-path: ./logs/
  log-name: console

bot:
  token: xxx
  poller-timeout: 3600 # second

send:
  range: 30 # day
  max-count: 10 # wechat

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_scut_notifier
  user: root
  password: 123

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 1000 # microsecond
  read-timeout: 1000
  write-timeout: 1000

task:
  cron: 0 0/1 * * * *
